import * as vscode from "vscode";
import * as path from "path";
import { execFile } from "child_process";
import { promisify } from "util";
import type { CustomerBrief } from "./plannerView";
import { buildArtifactPackage } from "./artifactPack";

const execFileP = promisify(execFile);

export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "customer";
}

/**
 * Materialize the generated markdown into the current workspace under
 *   ./engagements/<customer-slug>/<timestamp>/...
 * Returns the saved package folder URI, or undefined if no workspace is open.
 */
export async function autoSaveToWorkspace(
  brief: CustomerBrief,
  markdown: string
): Promise<vscode.Uri | undefined> {
  const ws = vscode.workspace.workspaceFolders?.[0];
  if (!ws) return undefined;
  const slug = slugify(brief.customerName);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const folder = vscode.Uri.joinPath(ws.uri, "engagements", slug, stamp);
  await vscode.workspace.fs.createDirectory(folder);
  const header = `<!-- Generated by Forge · ${new Date().toISOString()} -->\n`;
  for (const artifact of buildArtifactPackage(brief, markdown)) {
    const target = vscode.Uri.joinPath(folder, artifact.path);
    const dir = vscode.Uri.joinPath(folder, path.dirname(artifact.path));
    await vscode.workspace.fs.createDirectory(dir);
    const content = artifact.path === "ENGAGEMENT.md" ? header + artifact.content : artifact.content;
    await vscode.workspace.fs.writeFile(target, Buffer.from(content, "utf8"));
  }
  // Also persist the raw brief for reproducibility
  const briefFile = vscode.Uri.joinPath(folder, `brief.json`);
  await vscode.workspace.fs.writeFile(briefFile, Buffer.from(JSON.stringify(brief, null, 2), "utf8"));
  return folder;
}

/**
 * Create a GitHub repo for the customer and push the generated materials.
 * Requires the `gh` CLI to be installed and authenticated.
 */
export async function createCustomerRepo(opts: {
  brief: CustomerBrief;
  markdown: string;
  defaultVisibility: "private" | "internal" | "public";
  output: vscode.OutputChannel;
}): Promise<void> {
  const { brief, markdown, defaultVisibility, output } = opts;

  const confirm = await vscode.window.showWarningMessage(
    `Create a new GitHub repository for ${brief.customerName} and push the generated engagement materials?`,
    { modal: true, detail: "This will use the GitHub CLI (`gh`) under your logged-in identity." },
    "Create repo"
  );
  if (confirm !== "Create repo") return;

  const slug = slugify(brief.customerName);
  const defaultName = `${slug}-engagement`;
  const repoName = await vscode.window.showInputBox({
    prompt: "Repository name",
    value: defaultName,
    ignoreFocusOut: true,
    validateInput: (v) => (/^[\w.-]{1,100}$/.test(v) ? "" : "Invalid repo name")
  });
  if (!repoName) return;

  const visibilityPick = await vscode.window.showQuickPick(
    [
      { label: "Private", value: "private", picked: defaultVisibility === "private" },
      { label: "Internal", value: "internal", picked: defaultVisibility === "internal" },
      { label: "Public", value: "public", picked: defaultVisibility === "public" }
    ],
    { placeHolder: "Visibility" }
  );
  if (!visibilityPick) return;

  const owner = await vscode.window.showInputBox({
    prompt: "Owner (GitHub user or org) — leave empty for your personal account",
    placeHolder: "contoso-se or your-username",
    ignoreFocusOut: true
  });

  const ws = vscode.workspace.workspaceFolders?.[0];
  if (!ws) {
    vscode.window.showErrorMessage("Open a workspace folder first — Forge needs somewhere to stage the repo.");
    return;
  }

  const stagingDir = vscode.Uri.joinPath(ws.uri, "engagements", slug, "repo");
  await vscode.workspace.fs.createDirectory(stagingDir);

  for (const artifact of buildArtifactPackage(brief, markdown)) {
    const target = vscode.Uri.joinPath(stagingDir, artifact.path);
    const dir = vscode.Uri.joinPath(stagingDir, path.dirname(artifact.path));
    await vscode.workspace.fs.createDirectory(dir);
    await vscode.workspace.fs.writeFile(target, Buffer.from(artifact.content, "utf8"));
  }
  await vscode.workspace.fs.writeFile(
    vscode.Uri.joinPath(stagingDir, "brief.json"),
    Buffer.from(JSON.stringify(brief, null, 2), "utf8")
  );
  await vscode.workspace.fs.writeFile(
    vscode.Uri.joinPath(stagingDir, ".gitignore"),
    Buffer.from("node_modules/\n.env\n.DS_Store\n", "utf8")
  );

  const cwd = stagingDir.fsPath;

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: `Creating repo ${repoName}`, cancellable: false },
    async (prog) => {
      try {
        prog.report({ message: "Initializing git" });
        await run("git", ["init", "-b", "main"], cwd, output);
        await run("git", ["add", "."], cwd, output);
        await run(
          "git",
          [
            "-c", "user.email=forge@users.noreply.github.com",
            "-c", "user.name=Forge",
            "commit", "-m", "Initial engagement materials"
          ],
          cwd,
          output
        );

        prog.report({ message: "Creating GitHub repository" });
        const ownerRepo = owner ? `${owner}/${repoName}` : repoName;
        const ghArgs = [
          "repo", "create", ownerRepo,
          `--${visibilityPick.value}`,
          "--source", ".",
          "--push",
          "--description", `Engagement materials for ${brief.customerName} — generated by Forge`
        ];
        const { stdout } = await run("gh", ghArgs, cwd, output);

        const urlMatch = stdout.match(/https?:\/\/\S+/);
        const url = urlMatch?.[0];
        const action = await vscode.window.showInformationMessage(
          `Created ${ownerRepo}`,
          "Open in browser",
          "Copy URL"
        );
        if (url && action === "Open in browser") vscode.env.openExternal(vscode.Uri.parse(url));
        if (url && action === "Copy URL") await vscode.env.clipboard.writeText(url);
      } catch (err: any) {
        output.appendLine(`[forge] create-repo failed: ${err?.message ?? err}`);
        vscode.window.showErrorMessage(
          `Failed to create repo: ${err?.message ?? err}. See the Forge output channel.`
        );
      }
    }
  );
}

async function run(cmd: string, args: string[], cwd: string, output: vscode.OutputChannel) {
  output.appendLine(`$ ${cmd} ${args.join(" ")}   (in ${path.basename(cwd)})`);
  const { stdout, stderr } = await execFileP(cmd, args, { cwd, shell: false });
  if (stdout) output.appendLine(stdout.trim());
  if (stderr) output.appendLine(stderr.trim());
  return { stdout, stderr };
}
